app:
    path:     /
    defaults: { _controller: AppBundle:Default:index }


_test:
    path:     /test
    defaults: { _controller: AppBundle:Default:test }


_annonces:
    path:     /annonce
    defaults: { _controller: AppBundle:Default:annonce }



_club:
    path:     /club
    defaults: { _controller: ClubBundle:Default:index }

_events:
    path:     /events
    defaults: { _controller: AppBundle:Default:events }


_spotted:
    path:     /spotted
    defaults: { _controller: AppBundle:Default:spotted }


_docs:
    path:     /docs
    defaults: { _controller: AppBundle:Default:docs }

_admin:
    path:     /admin
    defaults: { _controller: AppBundle:Default:admin }

club_ajout:
    path:     /ajoutclub
    defaults: { _controller: ClubBundle:gererclub:Ajout }

club_affiche:
    path:     /afficheclub
    defaults: { _controller: ClubBundle:gererclub:Affiche }

club_recherche:
    path:     /rechercheclub
    defaults: { _controller: ClubBundle:gererclub:Recherche }

club_supprime:
    path:     /Deleteclub/{id}
    defaults: { _controller: ClubBundle:gererclub:Delete }

club_modifier:
    path:     /modifierclub/{id}
    defaults: { _controller: ClubBundle:gererclub:Modifier }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

