app:
    resource: '@AppBundle/Controller/'
    type: annotation
_test:
    path:     /test
    defaults: { _controller: AppBundle:Default:test }


_annonces:
    path:     /annonce
    defaults: { _controller: AppBundle:Default:annonce }



_club:
    path:     /club
    defaults: { _controller: AppBundle:Default:club }

_events:
    path:     /events
    defaults: { _controller: AppBundle:Default:events }


_spotted:
    path:     /spotted
    defaults: { _controller: AppBundle:Default:spotted }


_docs:
    path:     /docs
    defaults: { _controller: AppBundle:Default:docs }


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

