security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ETUDIANT: ROLE_ETUDIANT
        ROLE_ENSEIGNANT: ROLE_ENSEIGNANT
        ROLE_RESPOONSABLE_STORE: ROLE_RESPOONSABLE_STORE
        ROLE_RESPOONSABLE_CLUB: ROLE_RESPOONSABLE_CLUB

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: /
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/annonces , role: ROLE_ETUDIANT }
        - { path: ^/docs , role: ROLE_ENSEIGNANT }
        - { path: ^/events , role: ROLE_RESPOONSABLE_CLUB }
        - { path: ^/spotted , role: ROLE_ETUDIANT }
        - { path: ^/club , role: ROLE_RESPOONSABLE_CLUB }
