<?php

namespace EspritEntreAide\ClubBundle\Repository\Entity;

/**
 * clubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clubRepository extends \Doctrine\ORM\EntityRepository
{
}
