<?php

namespace Proxies\__CG__\EspritEntreAide\StoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Document extends \EspritEntreAide\StoreBundle\Entity\Document implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'id', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'nomDoc', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'source', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'etatDoc', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'dateUpload', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'id_annonce'];
        }

        return ['__isInitialized__', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'id', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'nomDoc', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'source', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'etatDoc', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'dateUpload', '' . "\0" . 'EspritEntreAide\\StoreBundle\\Entity\\Document' . "\0" . 'id_annonce'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Document $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomDoc($nomDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomDoc', [$nomDoc]);

        return parent::setNomDoc($nomDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomDoc', []);

        return parent::getNomDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAnnonce()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAnnonce', []);

        return parent::getIdAnnonce();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAnnonce($id_annonce)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAnnonce', [$id_annonce]);

        return parent::setIdAnnonce($id_annonce);
    }

    /**
     * {@inheritDoc}
     */
    public function setSource($source)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', [$source]);

        return parent::setSource($source);
    }

    /**
     * {@inheritDoc}
     */
    public function getSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', []);

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatDoc($etatDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatDoc', [$etatDoc]);

        return parent::setEtatDoc($etatDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatDoc', []);

        return parent::getEtatDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpload($dateUpload)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpload', [$dateUpload]);

        return parent::setDateUpload($dateUpload);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpload', []);

        return parent::getDateUpload();
    }

}
